version: '3'

services:
  openldap:
    image: osixia/openldap:latest
    container_name: ldap
    tty: true
    stdin_open: true
    volumes:
      - ./ldap/environment/config:/container/environment/01-custom
      - ./ldap/init:/container/service/slapd/assets/config/bootstrap/ldif/custom
    ports:
      - "389:389"
      - "636:636"
    domainname: ten1010.io # important: same as hostname
    hostname: ten1010.io

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: ldap-admin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ten1010.io
      PHPLDAPADMIN_HTTPS: false
    ports:
      - "8888:80"
    depends_on:
      - openldap
