version: '3'

services:
  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:
      LDAP_ORGANISATION: Example Me.
      LDAP_DOMAIN: example.com
      LDAP_BASE_DN: "" # default # if empty automatically set from LDAP_DOMAIN
      LDAP_ADMIN_PASSWORD: admin    # default
      LDAP_CONFIG_PASSWORD: config  # default
      KEEP_EXISTING_CONFIG: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "false"
    tty: true
    stdin_open: true
    volumes:
      - ./environment/config:/container/environment/01-custom
      - ./init:/container/service/slapd/assets/config/bootstrap/ldif/custom
    ports:
      - "389:389"
      - "636:636"
    domainname: example.com # important: same as hostname
    hostname: example.com

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ten1010.io
      PHPLDAPADMIN_HTTPS: false
    ports:
      - "8888:80"
    depends_on:
      - openldap
